#include <config.h>
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "libvirt-sandbox-protocol.h"

bool_t
xdr_GVirSandboxProtocolProc (XDR *xdrs, GVirSandboxProtocolProc *objp)
{

         if (!xdr_enum (xdrs, (enum_t *) objp))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_GVirSandboxProtocolType (XDR *xdrs, GVirSandboxProtocolType *objp)
{

         if (!xdr_enum (xdrs, (enum_t *) objp))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_GVirSandboxProtocolStatus (XDR *xdrs, GVirSandboxProtocolStatus *objp)
{

         if (!xdr_enum (xdrs, (enum_t *) objp))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_GVirSandboxProtocolHeader (XDR *xdrs, GVirSandboxProtocolHeader *objp)
{

         if (!xdr_GVirSandboxProtocolProc (xdrs, &objp->proc))
                 return FALSE;
         if (!xdr_GVirSandboxProtocolType (xdrs, &objp->type))
                 return FALSE;
         if (!xdr_GVirSandboxProtocolStatus (xdrs, &objp->status))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->serial))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_GVirSandboxProtocolMessageExit (XDR *xdrs, GVirSandboxProtocolMessageExit *objp)
{

         if (!xdr_int (xdrs, &objp->status))
                 return FALSE;
        return TRUE;
}
